#pragma once

const char *styles = ":root {\n"
"  --knob-outer: hsl(0, 1%, 13%);\n"
"  --knob-inner: hsl(0, 0%, 46%);\n"
"  --makita: hsl(185, 99%, 28%);\n"
"  --dewalt: hsl(43, 99%, 54%);\n"
"  --milwaukee: hsl(352, 100%, 43%);\n"
"}\n"
"\n"
".color_theme {\n"
"  background-color: var(--makita);\n"
"}\n"
"\n"
".color_theme_light {\n"
"  background-color: var(--makita);\n"
"}\n"
"\n"
".stack-container {\n"
"  position: relative;\n"
"}\n"
"\n"
".stack-container>div {\n"
"  position: absolute;\n"
"  top: 0;\n"
"  left: 0;\n"
"}\n"
"\n"
"body,\n"
"html {\n"
"  height: 100%;\n"
"  width: 100%;\n"
"  margin: 0;\n"
"  background-color: #4a4a4a;\n"
"  display: flex;\n"
"  justify-content: center;\n"
"}\n"
"\n"
"#mainframe {\n"
"  width: 100%;\n"
"  height: 100%;\n"
"  max-width: 500px;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  justify-content: space-between;\n"
"  align-items: center;\n"
"}\n"
"\n"
"#top-content {\n"
"  display: flex;\n"
"  flex-direction: row;\n"
"  justify-content: start;\n"
"  align-items: start;\n"
"  padding: 20px;\n"
"  width: 100%;\n"
"  height: 100%;\n"
"}\n"
"\n"
".menu_item {\n"
"  display: flex;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  width: 0px;\n"
"  height: 45px;\n"
"  margin: 0px;\n"
"  border-radius: 5%;\n"
"  transition: width 0.5s ease;\n"
"}\n"
"\n"
".menu_item.open {\n"
"  margin: 0px 2px;\n"
"  width: 45px;\n"
"  transition: all 0.5s ease;\n"
"}\n"
"\n"
".menu_item img {\n"
"  max-width: 90%;\n"
"  max-height: 90%;\n"
"  height: auto;\n"
"  width: auto;\n"
"}\n"
"\n"
"/* menu stuff */\n"
"\n"
".menu-toggle {\n"
"  height: 45px;\n"
"  width: 45px;\n"
"  margin: 0px 2px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
".menu-toggle-bar {\n"
"  width: 43px;\n"
"  height: 4px;\n"
"  border-radius: 4px;\n"
"  background-color: rgb(229, 229, 229);\n"
"  transition: all 0.5s ease;\n"
"\n"
"  &.menu-toggle-bar--top {\n"
"    margin-bottom: 10px;\n"
"  }\n"
"\n"
"  &.menu-toggle-bar--bottom {\n"
"    margin-top: 10px;\n"
"  }\n"
"\n"
"  .nav-open & {\n"
"    &.menu-toggle-bar--top {\n"
"      transform: translate(0, 18px) rotate(45deg);\n"
"      margin-bottom: 8px;\n"
"    }\n"
"\n"
"    &.menu-toggle-bar--middle {\n"
"      opacity: 0;\n"
"    }\n"
"\n"
"    &.menu-toggle-bar--bottom {\n"
"      transform: translate(0, -4px) rotate(-45deg);\n"
"      margin-top: 8px;\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"/*end menu stuff */\n"
"\n"
".topbottomborder {\n"
"  background-size: cover;\n"
"  height: 100px;\n"
"  overflow: hidden;\n"
"  width: 100%;\n"
"}\n"
"\n"
".topbottomborder img {\n"
"  width: 100%;\n"
"  height: 100%;\n"
"  object-fit: cover;\n"
"}\n"
"\n"
".knob_container {\n"
"  margin: 30px 30px 0px 30px;\n"
"  display: flex;\n"
"}\n"
"\n"
"#center_box {\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  align-items: center;\n"
"  justify-content: center;\n"
"  width: 100%;\n"
"  flex-grow: 1;\n"
"}\n"
"\n"
"#control_knob {\n"
"  width: 205px;\n"
"  height: 205px;\n"
"  border-radius: 50%;\n"
"  display: flex;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"  background-color: var(--knob-outer);\n"
"  font-size: 24px;\n"
"  position: relative;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"#line {\n"
"  width: 10%;\n"
"  height: 30%;\n"
"  position: absolute;\n"
"  top: 0;\n"
"  border-radius: 10px;\n"
"  background-color: var(--knob-outer);\n"
"  left: 45%;\n"
"}\n"
"\n"
"#inner_circle {\n"
"  width: 181px;\n"
"  height: 181px;\n"
"  background-color: var(--knob-inner);\n"
"  border-radius: 50%;\n"
"}\n"
"\n"
"#slide-container {\n"
"  background-size: cover;\n"
"  height: 80px;\n"
"  overflow: hidden;\n"
"  width: 100%;\n"
"  margin-top: 10px;\n"
"  display: flex;\n"
"  flex-direction: row;\n"
"  justify-content: center;\n"
"}\n"
"\n"
"#slide-container img {\n"
"  width: 50%;\n"
"  height: 100%;\n"
"  margin: 0px;\n"
"  object-fit: contain;\n"
"}\n"
"\n"
".tick_container {\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  justify-content: start;\n"
"  align-items: center;\n"
"  margin: -50px;\n"
"  padding: 0px 50px;\n"
"  width: 100%;\n"
"  height: 100%;\n"
"}\n"
"\n"
".tick_box {\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  justify-content: start;\n"
"  align-items: center;\n"
"  margin: -50px;\n"
"  padding: 0px 50px 100px 50px;\n"
"  width: 100%;\n"
"  height: 100%;\n"
"}\n"
"\n"
".tick_line {\n"
"  width: 4px;\n"
"  height: 40px;\n"
"  background-color: #000000;\n"
"  border-radius: 10px;\n"
"}\n"
"\n"
"#icon_container {\n"
"  width: 300px;\n"
"  height: 200px;\n"
"  margin: -100px -100px;\n"
"  padding: 50px 50px 0px 50px;\n"
"  display: flex;\n"
"  flex-direction: row;\n"
"  justify-content: space-between;\n"
"  align-items: start;\n"
"}\n"
"\n"
"#icon_container img {\n"
"  width: 40px;\n"
"  height: 40px;\n"
"}\n"
"\n"
".batt_row_container {\n"
"  height: 50%;\n"
"  width: 100%;\n"
"  display: flex;\n"
"  flex-direction: row;\n"
"}\n"
"\n"
".battery {\n"
"  margin: 10px;\n"
"  width: 25%;\n"
"  display: flex;\n"
"  flex-direction: column;\n"
"  justify-content: center;\n"
"  align-items: center;\n"
"}\n"
"\n"
".battery_top {\n"
"  width: 40%;\n"
"  height: 5%;\n"
"  border-style: solid;\n"
"  border-color: black;\n"
"  border-width: 3px 3px 0px 3px;\n"
"  border-top-left-radius: 10px;\n"
"  border-top-right-radius: 10px;\n"
"}\n"
"\n"
".battery_bottom {\n"
"  width: 100%;\n"
"  height: 95%;\n"
"  border: 3px solid black;\n"
"  border-radius: 10px;\n"
"  overflow: hidden;\n"
"}\n"
"\n"
".battery_title {\n"
"  font-family: \"Helvetica\", \"Arial\", sans-serif;\n"
"  font-weight: 600;\n"
"  font-size: 12pt;\n"
"  width: 130px;\n"
"  padding: 10px;\n"
"  color: aliceblue;\n"
"  background: #000000;\n"
"  text-align: center;\n"
"}\n"
"\n"
":root {\n"
"  --chamfer-width: 12px;\n"
"}\n"
"\n"
".chamfer {\n"
"  position: relative;\n"
"  clip-path: polygon(var(--chamfer-width) 0,\n"
"      calc(100% - var(--chamfer-width)) 0,\n"
"      100% var(--chamfer-width),\n"
"      100% calc(100% - var(--chamfer-width)),\n"
"      calc(100% - var(--chamfer-width)) 100%,\n"
"      var(--chamfer-width) 100%,\n"
"      0 calc(100% - var(--chamfer-width)),\n"
"      0 var(--chamfer-width));\n"
"}\n"
"\n"
".battery_level_top {\n"
"  width: 100%;\n"
"  height: 50%;\n"
"\n"
"}\n"
"\n"
".battery_level_bottom {\n"
"  width: 100%;\n"
"  height: 50%;\n"
"  background-color: green;\n"
"}"
                      "";

